image: Visual Studio 2017
configuration: Release

environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc

install:
  # Install Rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain stable --default-host %TARGET%
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
  # Clone submodules
  - move stl-thumb\target .
  - git submodule update --init --recursive
  - move target stl-thumb\

before_build:
  # Build stl-thumb
  - cd stl-thumb
  - cargo build --release

artifacts:
  - path: STLThumbSetupBundle\bin\$(CONFIGURATION)\STL-Thumb-Setup.exe
    name: STL-Thumb-Setup

cache:
  - C:\Users\appveyor\.cargo\registry
  - stl-thumb\target