image: Visual Studio 2017
configuration: Release
platform: x64

environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc

install:
  # Install Rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain stable --default-host %TARGET%
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
  # Clone submodules
  - if exist stl-thumb\target\ move stl-thumb\target .
  - git submodule update --init --recursive
  - if exist target\ move target stl-thumb\

before_build:
  # Build stl-thumb
  - cd stl-thumb
  - cargo build --release

build:
  project: STLThumbWindows.sln

artifacts:
  - path: STLThumbSetupBundle\bin\$(CONFIGURATION)\STL-Thumb-Setup.exe
    name: STL-Thumb-Setup

deploy:
  provider: GitHub
  auth_token:
    secure: FSAJyupMH2WSWbApwcD9alLMXmVzFE7fB7umbpowRJW6mzTehBUnVlzx+HCx8oik
  repository: unlimitedbacon/stl-thumb
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

cache:
  - C:\Users\appveyor\.cargo\registry
  - stl-thumb\target
